In [1]:
import numpy as np
import matplotlib

In [10]:
# Let's build a single neuron!

In [16]:
# This will be a single neuron with three inputs
# We will initialize our weights randomly, and our biases will be set to 0 to start

# Imagine the inputs as the data points we are giving our network

# input 1 has weight 0.2, input 2 has weight 0.8, and input 3 has weight -0.5
inputs = [1, 2, 3]
weights = [0.2, 0.8, -0.5]

In [17]:
# Let's randomly set a bias value of 2 for this example
bias = 2

In [18]:
# To get the output of this neuron we need to multiply each weight
# with it's corresponding input, and add the bias at the end
# output = weight * input + bias
output = (inputs[0] * weights[0] +
          inputs[1] * weights[1] +
          inputs[2] * weights[2] + bias)

print(output)

2.3


In [31]:
# Question: What would we need to change in our code if we were given another input?
# Answer: We have to add another input value and another weight value
# Let's do that here:
inputs = [1, 2, 3, 4]
weights = [0.2, 0.8, -0.5, 1.0]

In [32]:
output = (inputs[0] * weights[0] +
          inputs[1] * weights[1] +
          inputs[2] * weights[2] +
          inputs[3] * weights[3] + bias)

print(output)

# Quiz: If anyone here is familiar with linear algebra or matrix multiplication,
# what are we doing in the output above? What name do we give this mathematical operation?

6.3


In [33]:
# That was great - but it's really simple!
# What if we wanted to create a layer of neurons instead?

# In this scenario, if we want to add more neurons, what needs to change?
# What should we add to our code to create a layer of neurons?
# Do we need more inputs? Or will the inputs remain the same?
# Do we need more weights? What about biases?

# Answer: We have the same number of inputs because the neurons are in the same layer
# But every neuron in the layer needs its own set of weights and its own bias
inputs = [1, 2, 3, 4]

weights1 = [0.2, 0.8, -0.5, 1]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]

bias1 = 2
bias2 = 3
bias3 = 0.5

outputs = [

    # Neuron 1:
    inputs[0]*weights1[0] +
    inputs[1]*weights1[1] +
    inputs[2]*weights1[2] +
    inputs[3]*weights1[3] + bias1,

    # Neuron 2:
    inputs[0]*weights2[0] +
    inputs[1]*weights2[1] +
    inputs[2]*weights2[2] +
    inputs[3]*weights2[3] + bias2,

    # Neuron 3:
    inputs[0]*weights3[0] +
    inputs[1]*weights3[1] +
    inputs[2]*weights3[2] +
    inputs[3]*weights3[3] + bias3]

print (outputs)

[6.3, 0.45999999999999996, 3.69]


In [34]:
# What we created is a fully-connected neural network
# This is because each neuron is connected to every other
# neuron in the previous layer

# Imagine what it would be like to manually code a neural network
# with thousands or even millions of individual neurons?

In [35]:
inputs = [1, 2, 3, 2.5]

weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

# Output of current layer
layer_outputs = []

# loop through the neurons
# use zip to iterate over multiple iterables simultaneously
for neuron_weights, neuron_bias in zip(weights, biases):
    neuron_output = 0

    for n_input, weight in zip(inputs, neuron_weights):
        neuron_output += n_input*weight

    # add bias at the end of calculation for each neuron
    neuron_output += neuron_bias

    # generate list of results from layer of neurons
    layer_outputs.append(neuron_output)

print(layer_outputs)

[4.8, 1.21, 2.385]


In [36]:
# But why aren't we using numpy? wouldn't that be more efficient?

# Yes, of course, but we need to understand some math first:

In [37]:
# To perform efficient machine learning computations we need dot product
a = [1, 2, 3]
b = [2, 3, 4]
dot_product = a[0]*b[0] + a[1]*b[1] + a[2]*b[2]
print(dot_product)

# What if A and B above are secretly just weights and biases?
# Well...Let's build neurons with numpy now

20


In [38]:
# First thing: import numpy, and create weights and biases again
# then we will use dot product from numpy to compute our output
import numpy as np

inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0
outputs = np.dot(weights, inputs) + bias
print(outputs)

4.8


In [39]:
# What about a layer of neurons with numpy?
inputs = [1.0, 2.0, 3.0, 2.5]

weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2.0, 3.0, 0.5]

layer_outputs = np.dot(weights, inputs) + biases
print(layer_outputs)

# Remember: the equation for this is simply inputs * weights + bias
# That's it!
# NP.dot treats the above matrix as a list of vectors and simply performs
# dot product on each one with it's corresponding vector

[4.8   1.21  2.385]


In [39]:
# What do our inputs become if we want to train our network?

# simply, we create batches of inputs:
# this is what an example data set could look like for the model
inputs = [[1.0, 2.0, 3.0, 2.5], [0, 5, 3, 8], [1, 5, 7, 9]]

In [40]:
# How do we train our model on multiple batches of inputs?
# We simply have to tranpose our weight matrix so that
# we get all combinations of inputs and weight multiplications
# To do that, we simply take the previous code, and tranpose
# the weight matrix by adding a .T to the end - prett easy!
# Transposing a matrix just means that the columns become the rows
# and the rows become the columns, nothing crazy to understand at all.

inputs = [[1.0, 2.0, 3.0, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2.0, 3.0, 0.5]

layer_outputs = np.dot(inputs, np.array(weights).T) + biases
print(layer_outputs)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


In [ ]:
# That is all for now, next time we will get into adding layers to the neural network!